# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2b492b2af9fc9ef2151a12aec6ce84b3"
name = "shop-chat-agent"
handle = "shop-chat-agent-312"
application_url = "https://shop-chat-agent-lively-fog-4926.fly.dev/"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "customer_read_customers,customer_read_orders,customer_read_store_credit_account_transactions,customer_read_store_credit_accounts,unauthenticated_read_product_listings"

[auth]
redirect_urls = ["https://shop-chat-agent-lively-fog-4926.fly.dev/auth/callback", "https://shop-chat-agent-lively-fog-4926.fly.dev/auth/shopify/callback", "https://shop-chat-agent-lively-fog-4926.fly.dev/api/auth/callback"]

[pos]
embedded = false
